language: python
python:
  - "3.5"
before_install:
  - pip install git+ssh://git@github.com/anenriquez/mrta_allocation.git@develop
  - pip install git+ssh://git@github.com/anenriquez/mrta_datasets.git@develop
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python test/update_stn.py
